[package]
name = "using_trait_bounds_to_conditionally_implement_methods"
version = "0.1.0"
authors = ["Abdul Fatir <a.fatir@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
