[package]
name = "moving_ownership_to_closure_with_move"
version = "0.1.0"
authors = ["Abdul Fatir <a.fatir@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
